# Generated by Django 4.1.1 on 2022-09-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('DOJ', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
